In [0]:
import numpy as np

### 1. Criar um array com 10 números inteiros aleatórios entre 1 e 50 e calcular a média e o desvio padrão

In [0]:
array = np.random.randint(1, 51, size=10)

media = np.mean(array)
desvio_padrao = np.std(array)

print("Array: ", array)
print("Média: ", media)
print("Desvio padrão: ", desvio_padrao)

Array:  [46 16 31  4 13 31  1 27 22 26]
Média:  21.7
Desvio padrão:  12.884486796143648


### 2. Criar um array de 10 números aleatórios e calcular a raiz quadrada de todos os valores menores ou iguais a 0,5

In [0]:
array = np.random.rand(10)
raiz_quadrada = np.sqrt(array[array <= 0.5])

print("Array: ", array)
print("Raiz quadrada dos valores menores ou iguais a 0,5: ", raiz_quadrada)

Array:  [0.138113   0.28588396 0.627467   0.86223818 0.45129468 0.16857057
 0.02506067 0.46884355 0.64733049 0.40286884]
Raiz quadrada dos valores menores ou iguais a 0,5:  [0.37163557 0.53468118 0.6717847  0.41057347 0.15830562 0.68472151
 0.6347195 ]


### 3. Criar uma matriz 3D de tamanho 3x3x3 com valores aleatórios e exibir o valor máximo de cada linha de cada matriz 2D dentro dessa matriz 3D

In [0]:
matriz = np.random.rand(3, 3, 3)

for i in range(3):
    print("Máximo da linha ", i+1, " de cada matriz 2D:")
    print(np.max(matriz[i], axis=1))
    print("-------------------------")

Máximo da linha  1  de cada matriz 2D:
[0.90468241 0.81345199 0.94166469]
-------------------------
Máximo da linha  2  de cada matriz 2D:
[0.7879036  0.96422137 0.9225326 ]
-------------------------
Máximo da linha  3  de cada matriz 2D:
[0.99084452 0.66137427 0.74136613]
-------------------------


### 4. Criar uma matriz de tamanho 5x5 com valores aleatórios e subtrair a média de cada linha dessa matriz

In [0]:
matriz = np.random.rand(5, 5)
media_linhas = np.mean(matriz, axis=1)
matriz_subtraida = matriz - media_linhas

print("Matriz original:")
print(matriz)
print("-------------------------")
print("Média de cada linha:")
print(media_linhas)
print("-------------------------")
print("Matriz com a média de cada linha subtraída:")
print(matriz_subtraida)

Matriz original:
[[0.81145372 0.73080572 0.84388135 0.65354689 0.12285179]
 [0.92549471 0.15051694 0.2982747  0.16746228 0.29009765]
 [0.25628799 0.37098603 0.58512186 0.0175061  0.8299852 ]
 [0.83901091 0.55028443 0.52253897 0.3413963  0.72387186]
 [0.96147727 0.66445129 0.26461655 0.57726507 0.16603713]]
-------------------------
Média de cada linha:
[0.6325079  0.36636926 0.41197744 0.5954205  0.52676946]
-------------------------
Matriz com a média de cada linha subtraída:
[[ 0.17894583  0.36443646  0.43190391  0.0581264  -0.40391767]
 [ 0.29298682 -0.21585232 -0.11370274 -0.42795822 -0.2366718 ]
 [-0.37621991  0.00461678  0.17314442 -0.57791439  0.30321575]
 [ 0.20650301  0.18391517  0.11056154 -0.25402419  0.19710241]
 [ 0.32896937  0.29808203 -0.14736089 -0.01815543 -0.36073233]]


### 5. Criar uma matriz de tamanho 4x4 com valores aleatórios e calcular a média e o desvio padrão das diagonais da matriz

In [0]:
matriz = np.random.rand(4, 4)
diagonal_principal = np.diag(matriz)
diagonal_secundaria = np.diag(np.fliplr(matriz))

media_diagonal_principal = np.mean(diagonal_principal)
media_diagonal_secundaria = np.mean(diagonal_secundaria)

desvio_padrao_diagonal_principal = np.std(diagonal_principal)
desvio_padrao_diagonal_secundaria = np.std(diagonal_secundaria)

print("Matriz:")
print(matriz)
print("-------------------------")
print("Diagonal principal:")
print(diagonal_principal)
print("-------------------------")
print("Diagonal secundária:")
print(diagonal_secundaria)
print("-------------------------")
print("Média da diagonal principal:", media_diagonal_principal)
print("Média da diagonal secundária:", media_diagonal_secundaria)
print("-------------------------")
print("Desvio padrão da diagonal principal:", desvio_padrao_diagonal_principal)
print("Desvio padrão da diagonal secundária:", desvio_padrao_diagonal_secundaria)

Matriz:
[[0.2238269  0.23327005 0.59310703 0.7784018 ]
 [0.13185587 0.46400284 0.40097085 0.36546534]
 [0.99316217 0.31571415 0.90331138 0.39847777]
 [0.91007156 0.20594263 0.05669546 0.81977996]]
-------------------------
Diagonal principal:
[0.2238269  0.46400284 0.90331138 0.81977996]
-------------------------
Diagonal secundária:
[0.7784018  0.40097085 0.31571415 0.91007156]
-------------------------
Média da diagonal principal: 0.6027302677618309
Média da diagonal secundária: 0.6012895898761668
-------------------------
Desvio padrão da diagonal principal: 0.2739856905257347
Desvio padrão da diagonal secundária: 0.24919669557287963
